CREATE TABLE EMPLOYEE(ID number(12) not null primary key,ENAME varchar2(60),Salary varchar2(50))
ALTER TABLE EMPLOYEE ADD gender  VARCHAR2(20);
ALTER TABLE EMPLOYEE DROP COLUMN GENDER;
ALTER TABLE EMPLOYEE MODIFY ID NUMBER(38);
commit;
select * from EMPLOYEE;
delete from Employee;
drop table employee

insert into EMPLOYEE(select rownum from user_objects);
select max(ID) from EMPLOYEE;
SELECT EMPLOYEE_SEQ.NEXTVAL FROM DUAL
drop SEQUENCE "EMPLOYEE.SEQ"
CREATE SEQUENCE  EMPLOYEE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
COMMIT;

Create TABLE DIRECT_CREDIT_OUTWARD_TXN(
   DCO_TXN_INF_ID NUMBER NOT NULL PRIMARY KEY,
   DCO_GRP_HDR_ID_TXN_INFO_FK NUMBER NOT NULL,
   TXN_REF VARCHAR2(16 CHAR),
   USER_REF VARCHAR2(35 CHAR),
   AMOUNT NUMBER(18 , 5),
   BENEF_BANK VARCHAR2(35 CHAR),
   BENEF_ACC VARCHAR2(30 CHAR),
   BENEF_NAME VARCHAR2(140 CHAR),
   BENEF_ID VARCHAR2(35 CHAR),
   BENEF_ID_TYPE VARCHAR2(35 CHAR),
   PURP_OF_TRANSFER VARCHAR2(10 CHAR),
   DETAILS_OF_PMTS VARCHAR2(140 CHAR),
   STATUS VARCHAR2(50 CHAR),
   DESCRIPTION VARCHAR2(500 CHAR),
   CBS_TRAN_REF VARCHAR2(40 CHAR),
   CBS_PAY_REF VARCHAR2(40 CHAR),
   EXEC_DESC VARCHAR2(2000 CHAR),
   END_TO_END_ID VARCHAR2(48 CHAR),
   MSG_ID VARCHAR2(25 CHAR),
   TXN_ID VARCHAR2(25 CHAR),
   CBO_GRP_STATUS VARCHAR2(40),
   FAULT_CODE VARCHAR2(40),
   FAULT_STRING VARCHAR2(500),
   CBO_TXN_STATUS VARCHAR2(40),
   CBS_REQUEST_MESSAGE CLOB
   );
   
   CREATE SEQUENCE  DCO_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
   COMMIT;
   
   delete from DIRECT_CREDIT_OUTWARD_TXN;
   commit;
   delete from Employee;
   
   select * from DIRECT_CREDIT_OUTWARD_TXN
   select * from Employee where object_id < 100;
   SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
   EXPLAIN PLAN FOR SELECT * FROM DUAL;
   
    CREATE SEQUENCE  DCO_TXN_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
    COMMIT;